### ISSUE TITLE
wrong register used for SPI_SHADER_REQ_CTRL on gfx10

### ISSUE THREAD

**Issue by airlied** [GPUOpen-Drivers/pal#30] opened 2019-07-16 05:37 UTC
Just noticed this on navi, but for SHADER_REQ_CNTL for vertex shaders it's using the wrong thing

I'm sure you've fixed it internally already but for the lols.

diff --git a/src/core/hw/gfxip/gfx9/gfx9PipelineChunkVsPs.cpp b/src/core/hw/gfxip/gfx9/gfx9PipelineChunkVsPs.cpp
index cab8947..6837818 100644
--- a/src/core/hw/gfxip/gfx9/gfx9PipelineChunkVsPs.cpp
+++ b/src/core/hw/gfxip/gfx9/gfx9PipelineChunkVsPs.cpp
@@ -440,7 +440,7 @@ void PipelineChunkVsPs::LateInit(
 
             if (IsGfx10(chipProps.gfxLevel))
             {
-                pUploader->AddShReg(Gfx10::mmSPI_SHADER_REQ_CTRL_PS, m_commands.sh.vs.shaderReqCtrlVs);
+                pUploader->AddShReg(Gfx10::mmSPI_SHADER_REQ_CTRL_VS, m_commands.sh.vs.shaderReqCtrlVs);
             }
         } // if enableNgg == false

**Comment by jinjianrong** [comment] 2019-08-14 07:08
The issue is fixed in latest code. Thanks

**Closed by jinjianrong** 2019-08-14 07:08 UTC
